version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: bautistadb
      
    restart: always
    networks:
      - bauti-app-network

  app:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-bauti712.git
      dockerfile: dockerfile
    depends_on:
      - mysqldb
    environment:
      - PASSWORD=12345
      - DBNAME=bautistadb
      - HOST=mysqldb
    restart: always
    networks:
      - bauti-app-network

  frontend:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-frontend-bauti712.git
      dockerfile: Dockerfile
    networks:
      - bauti-app-network

  web:
    image: nginx:1.17.1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # El archivo de configuración de nginx
      # - ./app:/usr/share/nginx/html  # Si necesitas montar la carpeta app
    networks:
      - bauti-app-network
    depends_on:
      - frontend
      - app
    
  # web:
  #   build:
  #     context: https://github.com/etec-integration-project/etec-pi-2024-proxy-bauti712.git
  #     dockerfile: dockerfile
  #   ports:
  #     - 9090:80
  #   depends_on:
  #     - frontend
  #     - app
  #   networks:
  #     - bauti-app-network
  

  proxy:
    build: https://raw.githubusercontent.com/etec-integration-project/etec-pi-2024-proxy-bauti712/refs/heads/main/dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - app
    networks:
      - bauti-app-network

networks:
  bauti-app-network:
    external: true